In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np

In [2]:
jan = pd.read_csv('monthly_data/rail-jan.csv')

In [3]:
jan['datetime'] = pd.to_datetime(jan['timestamp'], format='%Y-%m-%d %H:%M:%S')
jan.drop(columns = ['timestamp'], inplace=True)

In [4]:
jan.sort_values('datetime', inplace=True)

In [6]:
jan.reset_index(drop=True, inplace=True)

In [7]:
list(jan.columns.values)

['bearing',
 'blockID',
 'delay',
 'direction',
 'garage',
 'lastLocID',
 'lastStopSeq',
 'messageCode',
 'nextLocID',
 'nextStopSeq',
 'routeNumber',
 'signMessageLong',
 'tripID',
 'type',
 'vehicle_id',
 'vehicle_location_longitude',
 'vehicle_location_latitude',
 'datetime']

In [8]:
jan.messageCode.unique()

array([892, 975, 971, 929, 891, 978, 972, 970, 927, 968, 976, 907, 893,
       969, 974, 906, 900, 902, 894, 973, 965])

In [9]:
jan.signMessageLong.unique()

array(['MAX  Blue Line to Gresham',
       'MAX  Green Line to Clackamas Town Center',
       'MAX  Yellow Line to City Center/Milwaukie',
       'MAX  Red Line to City Center & Beaverton',
       'MAX  Blue Line to Hillsboro',
       'MAX  Green Line to City Center/PSU',
       'MAX  Yellow Line to Expo Center',
       'MAX  Orange Line to City Center/Expo Center',
       'MAX  Red Line to Airport', 'MAX  Orange Line to Milwaukie',
       'MAX  Green Line to Gateway TC',
       'MAX  Blue Line to Ruby Junction/E 197th Ave',
       'MAX  Blue Line to Willow Creek/SW 185th Ave',
       'MAX  Orange Line to City Center/PSU',
       'MAX  Yellow Line to Interstate/Rose Quarter',
       'MAX  Blue Line to Elmonica/170th', 'MAX  Blue Line to Rose Qtr',
       'MAX  Blue Line to City Center', 'MAX  Blue Line to Gateway TC',
       'MAX  Yellow Line to City Center/PSU', 'MAX  To City Center'],
      dtype=object)

In [10]:
jan.messageCode.nunique() == jan.signMessageLong.nunique()

True

In [16]:
jan.loc[jan.signMessageLong == 'MAX  Orange Line to Milwaukie'].head()

,bearing,blockID,delay,direction,garage,lastLocID,lastStopSeq,messageCode,nextLocID,nextStopSeq,routeNumber,signMessageLong,tripID,type,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime
44,203,9068,-234,1,RUBY,7606,7,968,13710,8,290,MAX Orange Line to Milwaukie,7004094,rail,534,-122.683077,45.508826,2017-01-01 00:00:30
46,203,9068,-234,1,RUBY,7606,7,968,13710,8,290,MAX Orange Line to Milwaukie,7004094,rail,537,-122.683077,45.508826,2017-01-01 00:00:30
63,202,9068,-273,1,RUBY,7618,6,968,7606,7,290,MAX Orange Line to Milwaukie,7004094,rail,534,-122.682921,45.509080,2017-01-01 00:00:58
64,175,9064,-85,1,RUBY,13717,15,968,13718,16,290,MAX Orange Line to Milwaukie,7004093,rail,412,-122.636496,45.459794,2017-01-01 00:00:58
65,175,9064,-85,1,RUBY,13717,15,968,13718,16,290,MAX Orange Line to Milwaukie,7004093,rail,420,-122.636496,45.459794,2017-01-01 00:00:58

In [45]:
orange = jan.loc[jan.signMessageLong == 'MAX  Orange Line to Milwaukie'].copy()

In [20]:
orange[['tripID', 'datetime', 'vehicle_id']].groupby([orange.tripID, orange.datetime.dt.hour]).nunique()

                  tripID  datetime  vehicle_id
tripID  datetime
7004093 0              1         2           2
7004094 0              1        11           2
7004095 0              1        17           2
7004096 0              1        16           2
7004097 0              1        15           2
        1              1         1           2
7004098 0              1         7           2
        1              1         9           2
7004099 0              1         1           2
        1              1        15           2
7004100 1              1        16           2
7004101 1              1        14           2
        2              1         2           2
7004102 1              1         6           2
        2              1        10           2
7004103 1              1         1           2
        2              1        16           2
7004104 2              1        16           2
7004105 2              1        13           2
        3              1         3           2
7004106 2              1         9           2
        3              1         8           2
7004107 3              1        14           2
7004108 3              1        16           2
7004109 3              1        15           2
        4              1         1           2
7004110 3              1         8           2
        4              1         8           2
7004111 4              1        16           2
7004112 4              1        16           2
...                  ...       ...         ...
7130440 2              1         8           2
7130441 2              1        16           2
7130442 2              1        16           2
7130443 2              1        13           2
        3              1         4           2
7130444 2              1         5           2
        3              1        11           2
7130445 2              1         1           2
        3              1        15           2
7130446 3              1        16           2
7130447 3              1        13           2
        4              1         3           2
7130448 3              1         8           2
        4              1         8           2
7130449 3              1         2           2
        4              1        15           1
7130450 4              1        16           2
7130451 4              1        15           2
        5              1         1           2
7130452 4              1         7           2
        5              1         9           2
7130453 5              1        16           2
7130454 5              1         5           2
        6              1        11           2
7130455 6              1        15           2
        7              1         1           2
7130456 7              1        16           2
7130457 7              1        13           2
        8              1         3           2
7130458 8              1        16           2

[1212 rows x 3 columns]

In [46]:
orange['hour'] = orange.datetime.dt.hour.copy()

In [47]:
orange['minute'] = orange.datetime.apply(lambda x: x.minute)

In [31]:
orange.loc[orange.tripID == 7130449].duplicated(subset=['hour'])

770472    False
770487     True
770570    False
770627     True
770699     True
770720     True
770811     True
770825     True
770895     True
770995     True
771073     True
771104     True
771152     True
771198     True
771270     True
771334     True
771473     True
dtype: bool

In [40]:
orange.loc[orange.tripID == 7130449].loc[orange.duplicated(subset=['minute', 'hour'])].head()

,bearing,blockID,delay,direction,garage,lastLocID,lastStopSeq,messageCode,nextLocID,nextStopSeq,routeNumber,signMessageLong,tripID,type,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
770472,178,9066,0,1,RUBY,7601,11,968,7601,1,290,MAX Orange Line to Milwaukie,7130449,rail,205,-122.675544,45.526736,2017-01-30 03:59:19,3,59
770487,178,9066,2,1,RUBY,7601,1,968,9303,2,290,MAX Orange Line to Milwaukie,7130449,rail,247,-122.675518,45.526135,2017-01-30 03:59:49,3,59
770570,178,9066,-59,1,RUBY,9303,2,968,7627,3,290,MAX Orange Line to Milwaukie,7130449,rail,205,-122.675425,45.523522,2017-01-30 04:02:17,4,2
770627,202,9066,-74,1,RUBY,7627,3,968,7646,4,290,MAX Orange Line to Milwaukie,7130449,rail,205,-122.676156,45.521377,2017-01-30 04:04:22,4,4
770699,201,9066,-87,1,RUBY,7646,4,968,7608,5,290,MAX Orange Line to Milwaukie,7130449,rail,205,-122.677941,45.518067,2017-01-30 04:06:34,4,6

In [43]:
orange.groupby(['routeNumber']).nunique()

,bearing,blockID,delay,direction,garage,lastLocID,lastStopSeq,messageCode,nextLocID,nextStopSeq,routeNumber,signMessageLong,tripID,type,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
routeNumber,,,,,,,,,,,,,,,,,,,,
290,77,13,1160,1,1,16,16,1,17,17,1,1,728,1,132,1039,1052,30628,24,60

In [48]:
orange.drop('routeNumber', 1, inplace=True)

In [49]:
orange.drop(['messageCode', 'garage', 'type', 'direction'], 1, inplace=True)

In [50]:
orange.head()

,bearing,blockID,delay,lastLocID,lastStopSeq,nextLocID,nextStopSeq,signMessageLong,tripID,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
44,203,9068,-234,7606,7,13710,8,MAX Orange Line to Milwaukie,7004094,534,-122.683077,45.508826,2017-01-01 00:00:30,0,0
46,203,9068,-234,7606,7,13710,8,MAX Orange Line to Milwaukie,7004094,537,-122.683077,45.508826,2017-01-01 00:00:30,0,0
63,202,9068,-273,7618,6,7606,7,MAX Orange Line to Milwaukie,7004094,534,-122.682921,45.509080,2017-01-01 00:00:58,0,0
64,175,9064,-85,13717,15,13718,16,MAX Orange Line to Milwaukie,7004093,412,-122.636496,45.459794,2017-01-01 00:00:58,0,0
65,175,9064,-85,13717,15,13718,16,MAX Orange Line to Milwaukie,7004093,420,-122.636496,45.459794,2017-01-01 00:00:58,0,0

In [51]:
orange.sort_values('datetime', inplace=True)
orange.reset_index(drop=True, inplace=True)

In [52]:
list(orange.columns.values)

['bearing',
 'blockID',
 'delay',
 'lastLocID',
 'lastStopSeq',
 'nextLocID',
 'nextStopSeq',
 'signMessageLong',
 'tripID',
 'vehicle_id',
 'vehicle_location_longitude',
 'vehicle_location_latitude',
 'datetime',
 'hour',
 'minute']

In [53]:
orange.head()

,bearing,blockID,delay,lastLocID,lastStopSeq,nextLocID,nextStopSeq,signMessageLong,tripID,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
0,203,9068,-234,7606,7,13710,8,MAX Orange Line to Milwaukie,7004094,534,-122.683077,45.508826,2017-01-01 00:00:30,0,0
1,203,9068,-234,7606,7,13710,8,MAX Orange Line to Milwaukie,7004094,537,-122.683077,45.508826,2017-01-01 00:00:30,0,0
2,202,9068,-273,7618,6,7606,7,MAX Orange Line to Milwaukie,7004094,534,-122.682921,45.509080,2017-01-01 00:00:58,0,0
3,175,9064,-85,13717,15,13718,16,MAX Orange Line to Milwaukie,7004093,412,-122.636496,45.459794,2017-01-01 00:00:58,0,0
4,175,9064,-85,13717,15,13718,16,MAX Orange Line to Milwaukie,7004093,420,-122.636496,45.459794,2017-01-01 00:00:58,0,0

In [60]:
orange.groupby(['nextLocID']).nunique()

,bearing,blockID,delay,lastLocID,lastStopSeq,nextLocID,nextStopSeq,signMessageLong,tripID,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
nextLocID,,,,,,,,,,,,,,,
7601,1,13,121,1,4,1,1,1,246,69,2,2,311,21,48
7606,5,13,536,1,1,1,1,1,715,131,210,211,1873,24,60
7608,4,13,506,1,1,1,1,1,724,132,37,38,1930,24,60
7618,1,13,534,1,1,1,1,1,724,132,9,9,1969,24,60
7627,5,13,461,1,1,1,1,1,724,132,19,28,1948,24,60
7646,3,13,489,1,1,1,1,1,725,132,59,59,1943,24,60
9303,1,13,337,1,1,1,1,1,597,132,4,4,1598,24,60
13710,5,13,535,1,1,1,1,1,727,132,5,5,1959,24,60
13711,3,13,530,1,1,1,1,1,725,131,7,5,1948,24,60
13712,14,13,552,1,1,1,1,1,725,131,156,142,1942,24,60
13713,23,13,559,1,1,1,1,1,725,131,297,160,1927,24,60
13714,6,13,568,1,1,1,1,1,725,132,42,42,1924,24,60
13715,10,13,579,1,1,1,1,1,724,131,163,317,1912,24,60
13716,7,13,581,1,1,1,1,1,724,131,14,17,1934,23,60
13717,3,13,598,1,1,1,1,1,724,131,7,7,1912,23,60
13718,3,13,604,1,1,1,1,1,725,131,6,6,1916,24,60
13720,4,13,629,1,1,1,1,1,725,132,4,4,1921,24,60

In [62]:
orange.loc[orange.nextLocID == 7601].groupby(['vehicle_location_longitude', 'vehicle_location_latitude']).nunique()

,,bearing,blockID,delay,lastLocID,lastStopSeq,nextLocID,nextStopSeq,signMessageLong,tripID,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
vehicle_location_longitude,vehicle_location_latitude,,,,,,,,,,,,,,,
-122.675544,45.526736,1,13,117,1,3,1,1,1,241,69,1,1,305,21,48
-122.675542,45.526701,1,3,6,1,2,1,1,1,5,11,1,1,6,2,5

In [64]:
orange.loc[orange.nextLocID == 9303].groupby(['vehicle_location_longitude', 'vehicle_location_latitude']).nunique()

,,bearing,blockID,delay,lastLocID,lastStopSeq,nextLocID,nextStopSeq,signMessageLong,tripID,vehicle_id,vehicle_location_longitude,vehicle_location_latitude,datetime,hour,minute
vehicle_location_longitude,vehicle_location_latitude,,,,,,,,,,,,,,,
-122.675544,45.526736,1,12,24,1,1,1,1,1,54,33,1,1,55,19,21
-122.675542,45.526701,1,2,2,1,1,1,1,1,2,4,1,1,2,2,2
-122.675518,45.526135,1,13,290,1,1,1,1,1,577,132,1,1,1433,24,60
-122.675465,45.524836,1,12,81,1,1,1,1,1,92,92,1,1,108,21,40

In [70]:
jan.loc[jan.nextLocID == 7601].groupby(['vehicle_location_longitude', 'vehicle_location_latitude', 'delay']).nunique()

                                                            bearing  blockID  \
vehicle_location_longitude vehicle_location_latitude delay
-122.676592                45.527812                  10          1        1
-122.676591                45.527773                 -231         1        1
-122.676562                45.527961                 -1000        1        1
-122.676506                45.528018                 -315         1        1
-122.676459                45.528046                 -188         1        1
-122.676262                45.528087                 -240         1        1
-122.675695                45.528102                 -117         1        1
-122.675544                45.526736                 -1000        1        2
                                                     -648         1        1
                                                     -628         1        1
                                                     -611         1        1
                                                     -581         1        1
                                                     -555         1        1
                                                     -471         1        1
                                                     -437         1        1
                                                     -422         1        1
                                                     -417         1        1
                                                     -410         1        1
                                                     -352         1        1
                                                     -351         1        1
                                                     -290         1        1
                                                     -276         1        1
                                                     -261         1        1
                                                     -241         1        1
                                                     -240         1        1
                                                     -220         1        1
                                                     -219         1        1
                                                     -216         1        1
                                                     -205         1        1
                                                     -193         1        1
...                                                             ...      ...
-122.665867                45.530199                  3           1        1
                                                      4           1        4
                                                      5           1        5
                                                      6           1        4
                                                      7           1        1
                                                      8           1        2
                                                      9           1        2
                                                      10          1        2
                                                      11          1        1
                                                      12          1        3
                                                      14          1        1
                                                      15          1        1
                                                      16          1        2
                                                      17          1        2
                                                      18          1        1
                                                      19          1        1
                                                      21          1        2
                                                      22          1        3
                                                      23          1        1
                                                      24          1        1
                                                      27          1        1
                                                      29          1        2
                                                      35          1        2
                                                      43          1        1
                                                      44          1        1
                                                      51          1        1
                                                      57          1        1
                                                      62          1        1
                                                      64          1        1
                                                      71          1        1

                                                            delay  direction  \
vehicle_location_longitude vehicle_location_latitude delay
-122.676592                45.527812                  10        1          1
-122.676591                45.527773                 -231       1          1
-122.676562                45.527961                 -1000      1          1
-122.676506                45.528018                 -315       1          1
-122.676459                45.528046                 -188       1          1
-122.676262                45.528087                 -240       1          1
-122.675695                45.528102                 -117       1          1
-122.675544                45.526736                 -1000      1          1
                                                     -648       1          1
                                                     -628       1          1
                                                     -611       1          1
                                                     -581       1          1
                                                     -555       1          1
                                                     -471       1          1
                                                     -437       1          1
                                                     -422       1          1
                                                     -417       1          1
                                                     -410       1          1
                                                     -352       1          1
                                                     -351       1          1
                                                     -290       1          1
                                                     -276       1          1
                                                     -261       1          1
                                                     -241       1          1
                                                     -240       1          1
                                                     -220       1          1
                                                     -219       1          1
                                                     -216       1          1
                                                     -205       1          1
                                                     -193       1          1
...                                                           ...        ...
-122.665867                45.530199                  3         1          1
                                                      4         1          1
                                                      5         1          1
                                                      6         1          1
                                                      7         1          1
                                                      8         1          1
                                                      9         1          1
                                                      10        1          1
                                                      11        1          1
                                                      12        1          1
                                                      14        1          1
                                                      15        1          1
                                                      16        1          1
                                                      17        1          1
                                                      18        1          1
                                                      19        1          1
                                                      21        1          1
                                                      22        1          1
                                                      23        1          1
                                                      24        1          1
                                                      27        1          1
                                                      29        1          1
                                                      35        1          1
                                                      43        1          1
                                                      44        1          1
                                                      51        1          1
                                                      57        1          1
                                                      62        1          1
                                                      64        1          1
                                                      71        1          1

                                                            garage  lastLocID  \
vehicle_location_longitude vehicle_location_latitude delay
-122.676592                45.527812                  10         1          1
-122.676591                45.527773                 -231        1          1
-122.676562                45.527961                 -1000       1          1
-122.676506                45.528018                 -315        1          1
-122.676459                45.528046                 -188        1          1
-122.676262                45.528087                 -240        1          1
-122.675695                45.528102                 -117        1          1
-122.675544                45.526736                 -1000       1          1
                                                     -648        1          1
                                                     -628        1          1
                                                     -611        1          1
                                                     -581        1          1
                                                     -555        1          1
                                                     -471        1          1
                                                     -437        1          1
                                                     -422        1          1
                                                     -417        1          1
                                                     -410        1          1
                                                     -352        1          1
                                                     -351        1          1
                                                     -290        1          1
                                                     -276        1          1
                                                     -261        1          1
                                                     -241        1          1
                                                     -240        1          1
                                                     -220        1          1
                                                     -219        1          1
                                                     -216        1          1
                                                     -205        1          1
                                                     -193        1          1
...                                                            ...        ...
-122.665867                45.530199                  3          1          1
                                                      4          1          1
                                                      5          1          1
                                                      6          1          1
                                                      7          1          1
                                                      8          1          1
                                                      9          1          1
                                                      10         1          1
                                                      11         1          1
                                                      12         1          1
                                                      14         1          1
                                                      15         1          1
                                                      16         1          1
                                                      17         1          1
                                                      18         1          1
                                                      19         1          1
                                                      21         1          1
                                                      22         1          1
                                                      23         1          1
                                                      24         1          1
                                                      27         1          1
                                                      29         1          1
                                                      35         1          1
                                                      43         1          1
                                                      44         1          1
                                                      51         1          1
                                                      57         1          1
                                                      62         1          1
                                                      64         1          1
                                                      71         1          1

                                                            lastStopSeq  \
vehicle_location_longitude vehicle_location_latitude delay
-122.676592                45.527812                  10              1
-122.676591                45.527773                 -231             1
-122.676562                45.527961                 -1000            1
-122.676506                45.528018                 -315             1
-122.676459                45.528046                 -188             1
-122.676262                45.528087                 -240             1
-122.675695                45.528102                 -117             1
-122.675544                45.526736                 -1000            1
                                                     -648             1
                                                     -628             1
                                                     -611             1
                                                     -581             1
                                                     -555             1
                                                     -471             1
                                                     -437             1
                                                     -422             1
                                                     -417             1
                                                     -410             1
                                                     -352             1
                                                     -351             1
                                                     -290             1
                                                     -276             1
                                                     -261             1
                                                     -241             1
                                                     -240             1
                                                     -220             1
                                                     -219             1
                                                     -216             1
                                                     -205             1
                                                     -193             1
...                                                                 ...
-122.665867                45.530199                  3               1
                                                      4               1
                                                      5               2
                                                      6               2
                                                      7               1
                                                      8               1
                                                      9               1
                                                      10              1
                                                      11              1
                                                      12              1
                                                      14              1
                                                      15              1
                                                      16              1
                                                      17              1
                                                      18              1
                                                      19              1
                                                      21              1
                                                      22              1
                                                      23              1
                                                      24              1
                                                      27              1
                                                      29              1
                                                      35              2
                                                      43              1
                                                      44              1
                                                      51              1
                                                      57              1
                                                      62              1
                                                      64              1
                                                      71              1

                                                            messageCode  \
vehicle_location_longitude vehicle_location_latitude delay
-122.676592                45.527812                  10              1
-122.676591                45.527773                 -231             1
-122.676562                45.527961                 -1000            1
-122.676506                45.528018                 -315             1
-122.676459                45.528046                 -188             1
-122.676262                45.528087                 -240             1
-122.675695                45.528102                 -117             1
-122.675544                45.526736                 -1000            1
                                                     -648             1
                                                     -628             1